---
date: "2020-07-07"
title: "Workflow Digitaal Toetsen"
author: "Klinkenberg"
categories: [webinar, assessment]
# abstract = ""
# abstract_short = ""
subtitle: "Kennisdelingsessie Digitaal Toetsen en Toetsproces - UvA"
# event_url = ""
# location = "Online"

# selected = false
# math = true

# url_pdf = ""
# url_slides = ""
# url_video = "https://youtu.be/quxrQqjHlfA"

# # Optional featured image (relative to `static/img/` folder).
# [header]
# image = "headers/bubbles-wide.jpg"
# caption = "My caption :smile:"
---

<iframe width="100%" height="415" src="https://www.youtube.com/embed/quxrQqjHlfA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Duurzaam en robuuste inrichting van het digitale toetsproces.

Waar digitaal toetsen een paar maanden geleden nog slechts een optie was, is het nu plots een noodzaak geworden. Voor die afdelingen die het digitaal toetsen nog niet omarmt hadden kan dit behoorlijk overweldigend zijn. Nu de plannen voor het komend studiejaar gemaakt worden lijkt het ons het moment om met elkaar na te denken hoe met name digitale tentaminering idealiter ingeregeld zou moeten worden. Met die stip op de horizon kunnen digitale toets processen op een duurzame en robuuste manier worden ingericht.
 
In deze sessie zullen we in gaan op mogelijke werkprocessen, rollen rechten en het afbakenen en spreiden van verantwoordelijkheden. Met name dit laatste aspect moet de risico’s van uitval van medewerkers, gezien de COVID omstandigheden, in het toets proces minimaliseren.